INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.001", "Commoner", NULL, "Unit", NULL, "Non-attribute", "1", 1.0, NULL, NULL, NULL);
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.002", "Townsfolk", NULL, "Unit", NULL, "Non-attribute", "2", 2.0, NULL, NULL, "<b>Swarm</b> <i>(This unit is not destroyed upon taking damage.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.003", "Militia ", NULL, "Unit", NULL, "Non-attribute", "3", 4.0, NULL, NULL, "<b>Swarm</b> <i>(This unit is not destroyed upon taking damage.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.004", "Keep", NULL, "Fortification", NULL, "Non-attribute", NULL, NULL, 10.0, NULL, NULL);
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.005", "Watchtower", NULL, "Fortification", NULL, "Non-attribute", NULL, NULL, 7.0, NULL, "<b>Scout</b> <i>(Whenever an opponent places a reinforcement that shares a field with this fortification, reveal it.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.006", "Battle Cry", 1.0, "Order", NULL, "Non-attribute", "2", NULL, NULL, NULL, "All cards deployed this turn gain +1 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.007", "Recycle", 2.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Draw a card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.008", "In Ruins", 1.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Place a Ruins card at the bottom of any allied fortification stack.  You may use this card to place a Ruins in an empty fortification stack.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.009", "Well Rested ", 1.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Target leader regains +2 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.010", "Fury for the Fallen", 1.0, "Order", NULL, "Non-attribute", "1", NULL, NULL, NULL, "Target unit gains +2 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.011", "Attack Order", 1.0, "Order", NULL, "Non-attribute", "1", NULL, NULL, NULL, "Whenever target fortification takes damage this turn, it takes 1 additional damage.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.012", "Identification ", 1.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Reveal target reinforcement.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.013", "Brick and Mortar ", 1.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Attached fortifications regain +3 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.014", "Expansion Plan ", 1.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Attached fortifications regain +1 {l}, and the next time they would take damage this turn, prevent 3 damage.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.015", "Starvation ", 1.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Whenever an attached fortification would take damage this turn, prevent it unless your opponent discards 1 card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.016", "Dishonorable Discharge ", 1.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Return the first unit that arrives at each attached fortification to its recruitment rail; returned units cannot be redeployed this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.017", "Prepared Defensive ", 1.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Cards that arrive at an attached fortification have -2 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.018", "Eye for an Eye", 1.0, "Response", NULL, "Non-attribute", "0", NULL, NULL, NULL, "<b>Trigger:</b> An opponent draws a card as the result of an order.
<b>Response:</b> That opponent discards a card. Draw a card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.019", "Rapid Response", 1.0, "Response", NULL, "Non-attribute", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target leader takes damage from any source.  
<b>Response:</b> Target leader regains +1 {l}. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.020", "Road Less Traveled ", 1.0, "Response", NULL, "Non-attribute", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target card is deployed to a lane.
<b>Response:</b> Target card is deployed to a different, unoccupied lane. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.021", "Upcycle", 3.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Draw 2 cards.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.022", "Disarm", 2.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Disable target reinforcement until the end of your turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.023", "I want you!", 2.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Target leader gains +1 {h} until end of your next turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.024", "With Advantage! ", 2.0, "Order", NULL, "Non-attribute", "1", NULL, NULL, NULL, "If target card completes a successful attack this turn, deploy another unit to the same lane.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.025", "Repeat Offender ", 2.0, "Order", NULL, "Non-attribute", "2", NULL, NULL, NULL, "If target card deals damage with an attack this turn, recruit them to the same recruitment rail at the end of the deployment phase. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.026", "Indestructible", 2.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Attached fortifications cannot be reduced below 1 {l} this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.027", "Caltrops", 2.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Deal 1 damage to the first card that arrives at an attached fortification.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.028", "Meat Shield", 2.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "When an attached fortification is attacked, you may choose to destroy a unit from an allied recruitment rail and prevent damage equal to that unit's {p}. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.029", "Difficult Terrain", 2.0, "Response", NULL, "Non-attribute", "1", NULL, NULL, NULL, "<b>Trigger:</b> Target player deploys one or more units.
<b>Response:</b> Target player cannot deploy or redeploy any additional units this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.030", "Cost of War", 2.0, "Response", NULL, "Non-attribute", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target player pays one or more cards to fulfill the {c} of another card.
<b>Response:</b> Target player must pay an additional card (if possible).");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.031", "Referral Bonus", 3.0, "Order", NULL, "Non-attribute", "1", NULL, NULL, NULL, "All cards recruited this turn gain -1 {c}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.032", "Seek and Destroy ", 3.0, "Order", NULL, "Non-attribute", "1", NULL, NULL, NULL, "Destroy target reinforcement.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.033", "Another Castle", 3.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "If an attached fortification is destroyed, you may discard a card.  If you do, recreate it with full {l}. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.034", "Peace Offering ", 2.0, "Response", NULL, "Non-attribute", "1", NULL, NULL, NULL, "<b>Trigger:</b> Target player recruits one or more units.
<b>Response:</b> Target player cannot recruit any additional units this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.035", "Ruins", NULL, "Fortification", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "<b>Defenseless</b> <i>(This fortification does not prevent allied cards from being targeted for attacks.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.036", "Rust Monster", 1.0, "Response", NULL, "Non-attribute", "0", NULL, NULL, NULL, "<b>Trigger:</b> An <b>Equip</b> order is played.
<b>Response:</b> Destroy the <b>Equip</b> order.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.037", "Bareknuckle Brawlers", 2.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Destroy all <b>Equip</b> orders currently in play.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.038", "Boots at the Door", 2.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "When a card with an <b>Equip</b> order arrives at an attached fortification, you may discard a card. If you do, destroy all <b>Equip</b> orders attached to that card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.039", "Cycle", 1.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Draw a card, then discard a card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.040", "Warding Tower", NULL, "Fortification", NULL, "Non-attribute", NULL, NULL, 7.0, NULL, "Allied leaders in reserve that share a field with this fortification cannot be targeted by the effects of an opponent's orders. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.041", "Castle the King", 1.0, "Order", NULL, "Non-attribute", "0", NULL, NULL, NULL, "Switch the position of two allied leaders in reserve.  <i>(Recruited units are not affected by a change in leader position.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.042", "Casualties of War", 2.0, "Response", NULL, "Non-attribute", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target player pays one or more cards to fulfill the {c} of another card.
<b>Response:</b> Target player discards each card used for payment.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.NAT.043", "Bluff", 1.0, "Reinforcement", NULL, "Non-attribute", NULL, NULL, NULL, NULL, "Place this card on the bottom of your deck.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.GEN.001", "Ibn Rasa, Master of None", NULL, "Leader", "Generalist", "Non-attribute", "2", 2.0, 10.0, NULL, "Whenever an allied non-attribute card attacks, it gains +1 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.GEN.002", "Simple Robe", 3.0, "Order", "Generalist", "Non-attribute", "2", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order:</b> Parent card gains up to one attribute and up to one class name you choose until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.GEN.003", "Jack of All ", 1.0, "Order", "Generalist", "Non-attribute", "0", NULL, NULL, NULL, "Cards recruited this turn may be recruited to any allied recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.GEN.004", "Hamlet", NULL, "Fortification", "Generalist", "Non-attribute", NULL, NULL, 7.0, NULL, "<b>Rejuvenate</b> <i>(When an allied card is deployed to a lane shared by this fortification, that card regains +1 {l}.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.LMG.001", "Gerky, Conniving Goblin", NULL, "Leader", "Lootmonger", "Non-attribute", "1", 1.0, 6.0, 1.0, "Whenever a non-attribute reinforcement controlled by an opponent is revealed, draw a card, then discard a card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.LMG.002", "Kickstart", 2.0, "Order", "Lootmonger", "Non-attribute", "0", NULL, NULL, NULL, "If this is the first order you have played this turn, draw 2 cards.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.LMG.003", "Goblin's Greed", 3.0, "Order", "Lootmonger", "Non-attribute", "0", NULL, NULL, NULL, "Whenever you would draw one or more cards this turn as the result of an effect, draw a card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.LMG.004", "Junk Market", NULL, "Fortification", "Lootmonger", "Non-attribute", NULL, NULL, 6.0, NULL, "The first time a card arrives at this fortification each turn, draw a card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.WIZ.001", "Elq, Prismatic Witch", NULL, "Leader", "Wizard", "Arcane", "2", 1.0, 4.0, NULL, "<b>Spellcaster, Level 3</b> <i>(While this card is recruited, you may play a Spell card with Level 3 or less. If you do, remove this card from the recruitment rail.)</i>
Whenever you play a <b>Spell</b> card, you may double its {c}.  If you do, the card gains the <b>Prismatic</b> keyword.
(<b>Prismatic</b> <i>(This card's effects cannot be prevented or modified by another player.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.WIZ.002", "Bifrost, Prismatic Staff", 3.0, "Order", "Wizard", "Arcane", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent Wizard card gains +1 {p} and its damage cannot be prevented or modified by another player.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.WIZ.003", "Color Spray", 1.0, "Response", "Wizard", "Arcane", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target <b>Spell</b> card is played. 
<b>Response:</b> Target card gains the <b>Prismatic</b> keyword. 
(<b>Prismatic</b> <i>(This card's effects cannot be prevented or modified by another player.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.WIZ.004", "Outcast's Sanctum", NULL, "Fortification", "Wizard", "Arcane", NULL, NULL, 6.0, NULL, "<b>Scout</b> <i>(Whenever an opponent places a reinforcement that shares a field with this fortification, reveal it.)</i>
Wizard leaders in reserve that share a field with this fortification cannot be targeted by an opponent for attacks or card effects.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.001", "Celq, Celestial Queen", NULL, "Leader", "Astrologer", "Arcane", "3", NULL, 4.0, -1.0, "<b>Spellcaster, Level 1</b> <i>(While this card is recruited, you may play a Spell card with Level 1 or less. If you do, remove this card from the recruitment rail.)</i>
At the start of your turn, you may reveal up to one <b>Zodiac</b> card for each <b>Season</b> from your hand. If you do, draw a card for each card revealed this way.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.002", "Great Twins, Castor & Pollux", 1.0, "Response", "Astrologer", "Arcane", "3", NULL, NULL, NULL, "<b>Zodiac, Season of Spring</b>
<b>Trigger:</b> Target arcane leader attacks.
<b>Response:</b> Target arcane leader gains +2 {p} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.003", "Golden Ram, Krios", 2.0, "Response", "Astrologer", "Arcane", "2", NULL, NULL, NULL, "<b>Zodiac, Season of Spring</b>
<b>Trigger:</b> Target arcane leader attacks.
<b>Response:</b> Target arcane leader gains +2 {p} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.004", "Divine Bull, Tauros", 3.0, "Response", "Astrologer", "Arcane", "1", NULL, NULL, NULL, "<b>Zodiac, Season of Spring</b>
<b>Trigger:</b> Target arcane leader attacks.
<b>Response:</b> Target arcane leader gains +2 {p} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.005", "Breaching Crab, Karkinos", 1.0, "Response", "Astrologer", "Arcane", "3", NULL, NULL, NULL, "<b>Zodiac, Season of Summer</b>
<b>Trigger:</b> Target arcane leader takes damage.
<b>Response:</b> Prevent 2 of the damage, and if you do target arcane leader gains +2 {l} <i>(this can increase their {l} above its maximum value)</i>. 
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.006", "Solitary Goddess, Parthenos", 2.0, "Response", "Astrologer", "Arcane", "2", NULL, NULL, NULL, "<b>Zodiac, Season of Summer</b>
<b>Trigger:</b> Target arcane leader takes damage.
<b>Response:</b> Prevent 2 of the damage, and if you do target arcane leader gains +2 {l} <i>(this can increase their {l} above its maximum value)</i>. 
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.007", "Invincible Lion, Leon", 3.0, "Response", "Astrologer", "Arcane", "1", NULL, NULL, NULL, "<b>Zodiac, Season of Summer</b>
<b>Trigger:</b> Target arcane leader takes damage.
<b>Response:</b> Prevent 2 of the damage, and if you do target arcane leader gains +2 {l} <i>(this can increase their {l} above its maximum value)</i>. 
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.008", "Autumn Hunt, Skorpios", 1.0, "Response", "Astrologer", "Arcane", "3", NULL, NULL, NULL, "<b>Zodiac, Season of Autumn</b>
<b>Trigger:</b> You draw a card outside of the end phase as the result of an order or card effect.
<b>Response:</b> Target arcane leader gains a +1 {h} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.009", "Wise Centaur, Toxotes", 2.0, "Response", "Astrologer", "Arcane", "2", NULL, NULL, NULL, "<b>Zodiac, Season of Autumn</b>
<b>Trigger:</b> You draw a card outside of the end phase as the result of an order or card effect.
<b>Response:</b> Target arcane leader gains a +1 {h} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.010", "Grand Justicar, Zygos", 3.0, "Response", "Astrologer", "Arcane", "1", NULL, NULL, NULL, "<b>Zodiac, Season of Autumn</b>
<b>Trigger:</b> You draw a card outside of the end phase as the result of an order or card effect.
<b>Response:</b> Target arcane leader gains a +1 {h} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.011", "Cupbearer, Hydrokhoos", 1.0, "Response", "Astrologer", "Arcane", "3", NULL, NULL, NULL, "<b>Zodiac, Season of Winter</b>
<b>Trigger:</b> Target arcane leader is recruited.
<b>Response:</b> Target arcane leader gains a -1 {c} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.012", "Heroic Triton, Ikhthyes", 2.0, "Response", "Astrologer", "Arcane", "2", NULL, NULL, NULL, "<b>Zodiac, Season of Winter</b>
<b>Trigger:</b> Target arcane leader is recruited.
<b>Response:</b> Target arcane leader gains a -1 {c} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.013", "Lord of the Water, Aigokeros", 3.0, "Response", "Astrologer", "Arcane", "1", NULL, NULL, NULL, "<b>Zodiac, Season of Winter</b>
<b>Trigger:</b> Target arcane leader is recruited.
<b>Response:</b> Target arcane leader gains a -1 {c} counter.
<b>Unique</b> <i>(You can only include one copy of this card in your deck.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.AST.014", "Stargazer's Observatory", NULL, "Fortification", "Astrologer", "Arcane", NULL, NULL, 6.0, NULL, "<b>Scout</b> <i>(Whenever an opponent places a reinforcement that shares a field with this fortification, reveal it.)</i>
Once per turn, when you play a <b>Zodiac</b> card that targets a leader that shares a field with this fortification, you may search your deck for a <b>Zodiac</b> card with a different <b>Season</b>. If you do, add it to your hand.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.001", "Conjurer", NULL, "Unit", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spellcaster, Level 1</b> <i>(While this card is recruited, you may play a Spell card with Level 1 or less. If you do, remove this card from the recruitment rail.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.002", "Thaumaturge", NULL, "Unit", NULL, "Arcane", "1", 1.0, NULL, NULL, "<b>Spellcaster, Level 2</b> <i>(While this card is recruited, you may play a Spell card with Level 2 or less. If you do, remove this card from the recruitment rail.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.003", "Magus", NULL, "Unit", NULL, "Arcane", "2", 2.0, NULL, NULL, "<b>Spellcaster, Level 3</b> <i>(While this card is recruited, you may play a Spell card with Level 3 or less. If you do, remove this card from the recruitment rail.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.004", "Magi's Teachings", 1.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "Target card on a recruitment rail gains the <b>Spellcaster, Level 1</b> keyword until the end of this turn.
(<b>Spellcaster, Level 1</b> <i>(While this card is recruited, you may play a Spell card with Level 1 or less. If you do, remove this card from the recruitment rail.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.005", "Graduation", 1.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "Target <b>Spellcaster</b> card gains +1 <b>Level</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.006", "Firebolt", 1.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spell, Level 1</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Deal 1 damage to a target card that shares a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.007", "From the Spell Scroll", 1.0, "Order", NULL, "Arcane", "1", NULL, NULL, NULL, "The next <b>Spell</b> card played gains -1 <b>Level</b> (to a minimum of <b>Level 1</b>).");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.008", "Teleport", 1.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spell, Level 1</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Target card on a recruitment rail is moved to any other recruitment rail allied with that card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.009", "Reflection", 1.0, "Reinforcement", NULL, "Arcane", NULL, NULL, NULL, NULL, "Any card that arrives at an attached fortification is <b>Reflected</b>. 
(<b>Reflected</b> <i>(Target card is moved to the opposite lane an equal distance away from the center lane.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.010", "Translation", 1.0, "Reinforcement", NULL, "Arcane", NULL, NULL, NULL, NULL, "Any card that arrives at an attached fortification is <b>Translated</b>.
(<b>Translated</b> <i>(Target card is moved to an adjacent lane of your choice.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.011", "Illusory Keep", 1.0, "Reinforcement", NULL, "Arcane", NULL, NULL, NULL, NULL, "Replace an attached fortification with a different fortification card that you do not already control. All damage dealt to the original fortification is transfered to the new fortification.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.012", "Glowing Sigils", 1.0, "Reinforcement", NULL, "Arcane", NULL, NULL, NULL, NULL, "You may play a <b>Spell</b> card (you must still satisfy the <b>Spellcaster</b> requirement to play a <b>Spell</b> card).");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.013", "Scrying", 1.0, "Response", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Trigger:</b> A player draws one or more cards as the result of another card's effect.
<b>Response:</b> You may look at the cards that were drawn this way.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.014", "Spell Echo", 1.0, "Response", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Trigger:</b> An allied <b>Spell</b> card is played.
<b>Response:</b> You may play a <b>Spell</b> card with equal or lesser <b>Level</b> using the same <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.015", "Blink", 1.0, "Response", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target card arrives at a fortification.
<b>Response:</b> Target card is <b>Reflected</b>.
(<b>Reflected</b> <i>(Target card is moved to the opposite lane an equal distance away from the center lane.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.016", "Shift", 1.0, "Response", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target card arrives at a fortification.
<b>Response:</b> Target card is <b>Translated</b>.
(<b>Translated</b> <i>(Target card is moved to an adjacent lane of your choice.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.017", "Robes of the Archmagus", 2.0, "Order", NULL, "Arcane", "2", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order:</b> Parent card gains the <b>Spellcaster, Level 1</b> keyword.
(<b>Spellcaster, Level 1</b> <i>(While this card is recruited, you may play a Spell card with Level 1 or less. If you do, remove this card from the recruitment rail.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.018", "Fireball", 2.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spell, Level 2</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Deal 2 damage to a target card that shares a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.019", "Dualcast", 2.0, "Order", NULL, "Arcane", "1", NULL, NULL, NULL, "The next <b>Spell</b> card played may choose an additional target for its effect.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.020", "Haste", 2.0, "Order", NULL, "Arcane", "1", NULL, NULL, NULL, "<b>Spell, Level 2</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Target card that shares a field with this card's <b>Spellcaster</b> may attack an additional time this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.021", "Chain Lightning", 2.0, "Order", NULL, "Arcane", "1", NULL, NULL, NULL, "<b>Spell, Level 2</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Deal 2 Damage to all fortifications controlled by an opponent.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.022", "Time Skip", 2.0, "Reinforcement", NULL, "Arcane", NULL, NULL, NULL, NULL, "Discard a card. If you do, return all deployed cards to their recruitment rail; the deployment phase ends. 
<i>(Cards that have arrived or attacked this turn are not returned to the recruitment rail)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.023", "Divination", 2.0, "Response", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target allied card takes damage on your turn.
<b>Response:</b> Prevent the damage.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.024", "Spellish Rebuke", 2.0, "Response", NULL, "Arcane", "1", NULL, NULL, NULL, "<b>Trigger:</b> Target allied <b>Spellcaster</b> leader takes damage from an opponent's card. 
<b>Response:</b> You may play a <b>Spell</b> card using the target leader as the <b>Spellcaster</b>, and if you do ignore the recruitment requirement for that <b>Spell</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.025", "Robes of the Outcast Witch", 3.0, "Order", NULL, "Arcane", "3", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent <b>Spellcaster</b> card ignores the recruitment requirement for next <b>Spell</b> card played this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.026", "Meteor Shower", 3.0, "Order", NULL, "Arcane", "1", NULL, NULL, NULL, "<b>Spell, Level 3</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Deal 1 damage to any number of targets that share a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.027", "Flare", 3.0, "Order", NULL, "Arcane", "1", NULL, NULL, NULL, "<b>Spell, Level 3</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Deal 3 damage to a target card that shares a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.028", "College of Arcane Arts", NULL, "Fortification", NULL, "Arcane", NULL, NULL, 8.0, NULL, "Whenever an attached reinforcement is revealed, you may play a <b>Spell</b> card (you must still satisfy the <b>Spellcaster</b> requirement to play a <b>Spell</b> card).");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.029", "Extra Spell Slot", 1.0, "Order", NULL, "Arcane", "X+X", NULL, NULL, NULL, "Return a <b>Spell</b> card from your discard pile to your hand, where X is the <b>Level</b> of that <b>Spell</b> card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.030", "Counterspell", 2.0, "Response", NULL, "Arcane", "1", NULL, NULL, NULL, "<b>Spell, Level 2</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
<b>Trigger:</b> An order is played.
<b>Response:</b> Negate that order's effects and destroy it.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.031", "Phantasmal Armament", 2.0, "Order", NULL, "Arcane", "X", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
This card becomes a copy of target <b>Equip</b> order in play, where X is the <b>Rank</b> of the target order. Destroy this card if the original target order leaves play. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.032", "Gale", 1.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spell, Level 1</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Remove target unit from any recruitment rail that shares a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.033", "Storm", 2.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spell, Level 2</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Remove target leader from any recruitment rail that shares a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.ARC.034", "Hurricane", 3.0, "Order", NULL, "Arcane", "0", NULL, NULL, NULL, "<b>Spell, Level 3</b> <i>(This card can only be played by the effect of a Spellcaster card.)</i>
Remove any number of target cards from any recruitment rail that shares a field with this card's <b>Spellcaster</b>.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.BSK.001", "Lothar, Axe of the Asperlands", NULL, "Leader", "Berserker", "Melee", "3", 3.0, 12.0, -1.0, "<b>Armed</b> <i>(At the start of the game, attach a token Equip order to this card. The order you choose must share an attribute or class with this card.)</i>  
Whenever Lothar is dealt damage to his {l}, create a Rage counter on his card.  ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.BSK.002", "Seeing Bloodred", 3.0, "Order", "Berserker", "Melee", "2", NULL, NULL, NULL, "Remove all Rage counters from target Berserker leader.  Until the end of your turn, that leader may be redeployed once for each Rage counter removed this way.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.BSK.003", "Relentless Rage", 2.0, "Order", "Berserker", "Melee", "0", NULL, NULL, NULL, "Remove 1 Rage counter from target Berserker leader. If you do, until the start of your next turn that leader cannot be reduced below 1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.BSK.004", "Wartorn Battlefield", NULL, "Fortification", "Berserker", "Melee", NULL, NULL, NULL, NULL, "<b>Defenseless</b> <i>(This fortification does not prevent allied cards from being targeted for attacks.)</i>
When an allied leader is deployed from a field shared by this fortification, it gain +1 {p}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.BSK.005", "Blood-wretched Battle-axe", NULL, "Token Order", "Berserker", "Melee", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (deal 3 damage to parent leader):</b> Parent leader gains +1 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.PRM.001", "Vvulf, Pack Leader", NULL, "Leader", "Primalist", "Melee", "2", 2.0, 10.0, -1.0, "<b>Pack Hunter</b> <i>(This card may be deployed alongside any number of other Pack Hunter cards to the same lane.)</i>
<b>Armed</b> <i>(At the start of the game, attach a token Equip order to this card. The order you choose must share an attribute or class with this card.)</i>  
Whenever Vvulf is recruited, recruit a <i>Vvolf</i> to an allied recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.PRM.002", "Hunt", 2.0, "Order", "Primalist", "Melee", "1", NULL, NULL, NULL, "All Primalist cards deployed this turn gain +1 {p}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.PRM.003", "Family", 2.0, "Order", "Primalist", "Melee", "1", NULL, NULL, NULL, "Until the start of your next turn, whenever a <i>Vvolf</i> is recruited, recruit an additional <i>Vvolf</i> to the same recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.PRM.004", "Vvolves' Den", NULL, "Fortification", "Primalist", "Melee", NULL, NULL, NULL, NULL, "<b>Defenseless</b> <i>(This fortification does not prevent allied cards from being targeted for attacks.)</i>
Whenever a card arrives at this fortification, recruit a <i>Vvolf</i> to an allied recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.PRM.005", "Vvolf", NULL, "Token Unit", "Primalist", "Melee", "0", 1.0, NULL, NULL, "<b>Pack Hunter</b> <i>(This card may be deployed alongside any number of other Pack Hunter cards to the same lane.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.PRM.006", "Alpha's Cowl", NULL, "Token Order", "Primalist", "Melee", "2", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Order (1 {d}):</b> Create a <i>Vvolf</i> and add it to an allied reserve deck.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.001", "Fighter", NULL, "Unit", NULL, "Melee", "1", 2.0, NULL, NULL, NULL);
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.002", "Knight", NULL, "Unit", NULL, "Melee", "2", 2.0, NULL, NULL, "When this unit is deployed at the same time as a melee leader, it gains +1 {p}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.003", "Champion", NULL, "Unit", NULL, "Melee", "3", 3.0, NULL, NULL, "When this unit is deployed at the same time as a melee leader, it gains any modifications to {p} that the Leader has gained this turn. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.004", "A Bigger Sword", 2.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "Target leader gains a +1 {p} counter.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.005", "Second Wind", 1.0, "Order", NULL, "Melee", "0", NULL, NULL, NULL, "The next time target leader would take damage, prevent 1 damage and regain +1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.006", "Frontline Fighter", 1.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "You may destroy a melee unit on an allied recruitment rail.  If you do, place an allied Leader in reserve on the same recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.007", "Willingness to Wage", 1.0, "Order", NULL, "Melee", "0", NULL, NULL, NULL, "Target leader has -2 {c} until the end of your turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.008", "Overexert", 1.0, "Order", NULL, "Melee", "0", NULL, NULL, NULL, "Target leader has +2 {p} until the end of this turn.  You cannot recuit this leader this turn.  ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.009", "Get Through Me!", 1.0, "Reinforcement", NULL, "Melee", NULL, NULL, NULL, NULL, "When an attached fortification is attacked, you may choose to defend it with an allied leader. The leader you defend with becomes the new target of the attack.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.010", "Honorable Duel", 1.0, "Reinforcement", NULL, "Melee", NULL, NULL, NULL, NULL, "Whenever a card arrives at an attached fortification, that card deals no damage this turn unless it is an opposing leader card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.011", "Last Line of Defense", 1.0, "Reinforcement", NULL, "Melee", NULL, NULL, NULL, NULL, "Until the end of this turn, whenever an allied leader would take damage, they prevent 1 damage. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.012", "Back Home", 1.0, "Reinforcement", NULL, "Melee", NULL, NULL, NULL, NULL, "Whenever a unit arrives at an attached fortification, target leader gains +1 {l} (<i>this can increase their {l} above its maximum value</i>). ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.013", "Seek Vengeance ", 1.0, "Reinforcement", NULL, "Melee", NULL, NULL, NULL, NULL, "It an attached fortification is destroyed, you may place any number of melee leaders in reserve on allied recruitment rails. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.014", "Parry", 1.0, "Response", NULL, "Melee", "2", NULL, NULL, NULL, "<b>Trigger:</b> Target leader is attacked.
<b>Response:</b>  Damage from the attack is prevented.
When you play this card, you may discard a card. If you do, search your deck for a <i>Riposte</i> card and add it to your hand.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.015", "Riposte", 1.0, "Response", NULL, "Melee", "0", NULL, NULL, NULL, "<b>Trigger:</b> Parry is played and prevents the damage from an attack on a leader.
<b>Response:</b> Deal 3 damage to the attacking card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.016", "Twist the Knife", 1.0, "Response", NULL, "Melee", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target allied leader successfully attacks and deals damage to a fortification or leader.
<b>Response:</b> Target leader deals 1 additional damage with their attack.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.017", "Everywhere At Once", 2.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "If target leader is deployed to any lane this turn, you may redeploy them.  They must be redeployed to a different lane.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.018", "Return of the King", 2.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "If target melee leader is deployed this turn, you may recruit that leader for 0 {c} until the end of your turn.  ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.020", "Fractal Plate", 2.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Response (1 {d}):</b> 
<b>Trigger:</b> Parent leader takes damage from a source controlled by an opponent.
<b>Response:</b>  Prevent 1 of that damage.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.021", "Briared Cuirass", 2.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Response (1 {d}):</b> 
<b>Trigger:</b> Target leader takes damage from an attack.
<b>Response:</b>  Deal 2 damage to the attacking card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.022", "Foxholed Hero", 2.0, "Reinforcement", NULL, "Melee", NULL, NULL, NULL, NULL, "Whenever a card arrives at an attached fortification, you may remove a recruited leader from a recruitment rail.  If you do, deal damage to the arriving card equal to that leader's {p}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.023", "Requip", 2.0, "Response", NULL, "Melee", "0", NULL, NULL, NULL, "<b>Trigger:</b> An order <b>Equipped</b> to an allied leader would be destroyed.
<b>Response:</b> The order is not destroyed and remains <b>Equipped</b> to the leader.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.024", "Plus Ultra", 2.0, "Response", NULL, "Melee", "0", NULL, NULL, NULL, "<b>Trigger:</b> An order is played that increases a leader's {p}.
<b>Response:</b> That leader gains +1 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.019", "Bunker Buster Blade", 3.0, "Order", NULL, "Melee", "2", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent leader gains +2 {p} while attacking fortifications.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.025", "Ragnarok, Vorpal Blade", 3.0, "Order", NULL, "Melee", "2", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent leader gains +2 {p} while attacking other leaders.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.026", "Once They Know", 3.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "Whenever target melee leader would gain {p} this turn as the result of an order, response, or fortification, they gain an additional +1 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.027", "Indomitable", 3.0, "Response", NULL, "Melee", "1", NULL, NULL, NULL, "<b>Trigger:</b> Target allied leader takes damage that would reduce their {l} below 1.
<b>Response:</b> Prevent all damage dealt to that leader until the end of this turn.  ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.028", "Garrison", NULL, "Fortification", NULL, "Melee", NULL, NULL, 7.0, NULL, "Whenever you recruit a leader to a recruitment rail that shares a field with this fortification, the next unit you recruit with the same attribute(s) gains -1 {c}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.029", "Stationed", 1.0, "Order", NULL, "Melee", "0", NULL, NULL, NULL, "Target melee card on an allied recruitment rail is moved to an empty reinforcement zone attached to an allied fortification. The next time a card arrives at that fortification, the attached melee card becomes the target of that card's attack. If the attack does not destroy the attached melee card, return it to its original recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.030", "Bastard Sword", NULL, "Token Order", NULL, "Melee", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent leader gains +1 {p} while attacking other recruited leaders.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.031", "Broadhead Pike", NULL, "Token Order", NULL, "Melee", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent leader gains +1 {p} while attacking other leaders in reserve.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.032", "Rearm", 1.0, "Order", NULL, "Melee", "0", NULL, NULL, NULL, "Create a <b>Equip</b> order token that shares an attribute or class with an allied leader, then add it to your hand.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.033", "Armed to the Teeth", 2.0, "Order", NULL, "Melee", "0", NULL, NULL, NULL, "The first time each <b>Equip</b> order attached to target melee card is activated this turn, that activation gains -1 {d}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.034", "Steel-plated Maul", NULL, "Token Order", NULL, "Melee", "1", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Parent leader gains the <b>Knockback</b> keyword until the end of this turn.
(<b>Knockback</b> <i>(When this card attacks and deals damage to a target on a recruitment rail, that target is removed from the recruitment rail.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.MEL.035", "Wild Charge", 1.0, "Order", NULL, "Melee", "1", NULL, NULL, NULL, "The first unit that attacks this turn gains the <b>Knockback</b> keyword.
(<b>Knockback</b> <i>(When this card attacks and deals damage to a target on a recruitment rail, that target is removed from the recruitment rail.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.EXA.001", "Seraphim, Idol of Worship", NULL, "Leader", "Exarch", "Faith", "2", NULL, 10.0, 1.0, "<b>Worship, 2 Disciples (1 {d}):</b> Target <b>Persistence</b> card with no <b>Persist</b> counters gains +1 <b>Persist</b> counter. 
<i>(This effect can only be activated in your deployment phase while 2 allied Disciple cards share a recruitment rail with this Leader.)</i> ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.EXA.002", "Prayer to the Idol", 2.0, "Order", "Exarch", "Faith", "0", NULL, NULL, NULL, "Move any number of <b>Persist</b> counters from one <b>Persistence</b> card to another <b>Persistence</b> card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.EXA.003", "Statue of the Exarch", 3.0, "Reinforcement", "Exarch", "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
While this card is revealed in play, it is the only card that <b>Persist</b> counters must be removed from in the end phase. When this card leaves play, destroy all allied <b>Persistance</b> cards in play.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.EXA.004", "Crystalline Chapel", NULL, "Fortification", "Exarch", "Faith", NULL, NULL, 10.0, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
Whenever a <b>Persistence</b> card attached to this fortification is destroyed in the end phase, this card regains +2 {l}.
Whenever a card attached to this fortification would gain a <b>Persist</b> counter, you may instead add that counter to this card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.APS.001", "Father Azari, Golden Guidance", NULL, "Leader", "Apostle", "Faith", "1", NULL, 8.0, NULL, "<b>Worship, 1 Disciple (1 {d}):</b> Whenever an allied faith unit is deployed this turn, target allied card regains +1 {l}. 
<i>(This effect can only be activated in your deployment phase while 1 allied Disciple card shares a recruitment rail with this Leader.)</i> ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.APS.002", "Shepherd for All", 1.0, "Order", "Apostle", "Faith", "0", NULL, NULL, NULL, "All cards regain +1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.APS.003", "Lead to Enlightenment", 3.0, "Reinforcement", "Apostle", "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
While this card is revealed in play, whenever an allied card regains any {l} (except from <i>Lead to Enlightenment</i>), all other allied cards regain +1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.APS.004", "Radiant Sanctuary", NULL, "Fortification", "Apostle", "Faith", NULL, NULL, 6.0, NULL, "<b>Rejuvenate</b> <i>(When an allied card is deployed to a lane shared by this fortification, that card regains +1 {l}.)</i>
When this card would be destroyed, it instead remains in play at 0 {l} and gains the <b>Defenseless</b> keyword.
(<b>Defenseless</b> <i>(This fortification does not prevent allied cards from being targeted for attacks.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.001", "Share All in Her World", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "Each player targets one of their face down reinforcements and reveals it. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.002", "Her Hymn of Rejuvenation", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "All allied leaders regain +2 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.003", "Her Blessing of Light", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "Prevent the next 1 damage all allied cards take this turn. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.004", "Her Home for You", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "Target fortification regains +2 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.005", "Play Again, Her Hymn", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "Target one reinforcement that is revealed in play. Turn it face down, then you may reveal it.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.006", "Enchant, Her Golden Light", 1.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
Prevent the first 2 damage dealt to attached fortifications this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.007", "Prosperous Harvest, Her Gift", 1.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 2</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 2 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
While this card is revealed in play, whenever an attached fortification would regain {l}, it regains +1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.008", "Greet Thy Neighbor, Her Child", 1.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 2</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 2 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
While this card is revealed in play, attached fortifications cannot be targeted by the effects of an opponent's orders.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.009", "Her Gift of Golden Grain", 1.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
Attached fortifications regain +2 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.010", "Her Blessing, Divine", 1.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
Cards that arrive at attached fortifications have -1 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.011", "In Her Name", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "The next <b>Worship</b> effect you activate this turn gains -2 {d}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.012", "Her Presence, Emanating", 1.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i> 
Choose one attached fortification. While this card is revealed in play, it gain the <b>Sanctum</b> keyword.
(<b>Sanctum</b> <i>(Allied Worship effects require 1 less Disciple to activate.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.013", "Her Garb of Golden Order", 1.0, "Order", NULL, "Faith", "0", NULL, NULL, NULL, "<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order:</b> Parent card gains the <b>Disciple</b> keyword until the end of this turn.
(<b>Disciple</b> <i>(This card can be used to satisfy the Disciple requirement of another card's Worship effect while it shares a recruitment rail with that card.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.014", "Her Chapels, Restored", 2.0, "Order", NULL, "Faith", "1", NULL, NULL, NULL, "All allied faith fortifications regain +2 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.015", "Her Image, Everlasting", 2.0, "Order", NULL, "Faith", "1", NULL, NULL, NULL, "Target <b>Persistence</b> card gains +1 <b>Persist</b> counter. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.016", "She Sees All", 2.0, "Order", NULL, "Faith", "1", NULL, NULL, NULL, "All face down reinforcements are revealed.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.017", "Her Men, Unyielding", 2.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i> 
While this card is revealed in play, prevent all damage dealt to allied units.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.018", "For Her, They Follow", 2.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i> 
While this card is revealed in play, the first order you play each turn gains -1 {c}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.019", "To Her, They Come", 2.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i> 
While this card is revealed in play, the first card you recruit each turn gains -1 {c}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.020", "Flow, Her Radiant Embrace", 2.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
All allied cards regain +1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.021", "Come to Her, Stay with Her", 2.0, "Response", NULL, "Faith", "2", NULL, NULL, NULL, "<b>Trigger:</b> Target reinforcement is activated by a card arriving to its fortification.
<b>Response:</b> Target reinforcement gains the <b>Persistence, 1</b> keyword. 
(<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.022", "Against Her, They Relent", 3.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i> 
While this card is revealed in play, the first time an opponent pays one or more cards to fulfill the {c} of another card each turn, they pay an additional card (if possible).");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.023", "Peace Be Upon Her Land", 3.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "<b>Persistence, 1</b> <i>(This card is not destroyed after activation. When this card is revealed, it gains 1 Persist counter(s). In the end phase of your turn, remove 1 Persist counter from this card or destroy it.)</i>
While this card is revealed in play, all damage dealt on an opponent's turn is prevented and attached fortifications gain <i>""damage dealt to this fortification cannot be prevented""</i>.  If this card is attached to a <b>Defenseless</b> fortification, destroy it.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.024", "By Her Name, Return", 3.0, "Reinforcement", NULL, "Faith", NULL, NULL, NULL, NULL, "Replace this card with any faith reinforcement from your discard pile (except <i>By Her Name, Return</i>), then activate that reinforcement.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.025", "Devoted", NULL, "Unit", NULL, "Faith", "1", NULL, NULL, NULL, "<b>Disciple</b> <i>(This card can be used to satisfy the Disciple requirement of another card's Worship effect while it shares a recruitment rail with that card.)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.026", "Priest", NULL, "Unit", NULL, "Faith", "2", 1.0, NULL, NULL, "<b>Disciple</b> <i>(This card can be used to satisfy the Disciple requirement of another card's Worship effect while it shares a recruitment rail with that card.)</i>
When this unit is recruited, every card on the recruitment rail it was recruited to regains +1 {l}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.027", "Cleric", NULL, "Unit", NULL, "Faith", "2", 1.0, NULL, NULL, "<b>Disciple</b> <i>(This card can be used to satisfy the Disciple requirement of another card's Worship effect while it shares a recruitment rail with that card.)</i>
When this unit is deployed to a lane with a revealed <b>Persistence</b> card in it, it gains +2 {p} until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.028", "Her Hallowed Grounds", NULL, "Fortification", NULL, "Faith", NULL, NULL, 6.0, NULL, "<b>Sanctum</b> <i>(Allied Worship effects require 1 less Disciple to activate.)</i>
When this card would be destroyed, it instead remains in play at 0 {l} and gains the <b>Defenseless</b> keyword.
(<b>Defenseless</b> <i>(This fortification does not prevent allied cards from being targeted for attacks.)</i>)");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.FTH.029", "Her Gospel, Received", 2.0, "Response", NULL, "Faith", "0", NULL, NULL, NULL, "<b>Trigger:</b> A card is deployed.
<b>Response:</b> Target reinforcement is revealed.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.SCT.001", "Teyr, Treetop Watchman", NULL, "Leader", "Scout", "Ranged", "2", 2.0, 6.0, 1.0, "<b>Long-distance</b>, <b>Reload</b>
Whenever a <b>Long-distance</b> card skips the arrival step, you may reveal target face down reinforcement in the lane that card was deployed to.  
When this card is recruited, it gains 2 Ammo counters.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.SCT.002", "Bird's Eye View", 1.0, "Order", "Scout", "Ranged", "1", NULL, NULL, NULL, "Until the start of your next turn, whenever a reinforcement controlled by an opponent would be revealed, instead reveal all of their face down reinforcements.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.SCT.003", "Misfortune, Avoided", 2.0, "Order", "Scout", "Ranged", "1", NULL, NULL, NULL, "Until the start of your next turn, whenever a reinforcement controlled by an opponent is revealed, that reinforcement is placed on the bottom of their deck.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.SCT.004", "Crow's Nest", NULL, "Fortification", "Scout", "Ranged", NULL, NULL, 7.0, NULL, "<b>Scout</b> <i>(Whenever an opponent places a reinforcement that shares a field with this fortification, reveal it.)</i>
Allied fortifications that share a lane with this fortification gain the <b>Scout</b> keyword while it is in play.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.DDE.001", "Sandpit Christy, Heartseeker", NULL, "Leader", "Deadeye", "Ranged", "3", 3.0, 6.0, -1.0, "<b>Long-distance</b>, <b>Piercing</b>, <b>Reload</b>
When this card is recruited, it gains 3 Ammo counters.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.DDE.002", "Fire for Effect", 2.0, "Order", "Deadeye", "Ranged", "1", NULL, NULL, NULL, "Whenever a card with <b>Piercing</b> and <b>Long-distance</b> deploys this turn, it may activate the effect of both keywords without removing any Ammo counters.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.DDE.003", "Death's Judgement", 2.0, "Response", "Deadeye", "Ranged", "1", NULL, NULL, NULL, "<b>Trigger:</b> Target <b>Piercing</b> card skips the arrival step and deals damage to a fortification.
<b>Response:</b> Target card may target any card controlled by an opponent for its piercing damage.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.DDE.004", "Predator's Loophole", NULL, "Fortification", "Deadeye", "Ranged", NULL, NULL, NULL, NULL, "<b>Defenseless</b> <i>(This fortification does not prevent allied cards from being targeted for attacks.)</i>
Whenever a Deadeye leader is deployed from a field shared by this fortification, it may declare attack targets as though it were deployed to any lane from an adjacent field.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.001", "Bowman", NULL, "Unit", NULL, "Ranged", "2", 1.0, NULL, NULL, "<b>Long-distance</b> <i>(When this card is deployed, you may remove an Ammo counter from it. If you do, this card skips the arrival step.)</i>
<b>Reload</b> <i>(At the end of your deployment phase, if this card was deployed, you may remove an Ammo counter from it. If you do, place it back on the recruitment rail it was deployed from.)</i>
When this card is recruited, it gains 2 Ammo counters.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.002", "Arbalist ", NULL, "Unit", NULL, "Ranged", "2", 1.0, NULL, NULL, "<b>Piercing</b> <i>(When this card deals damage to a fortification, you may remove an Ammo counter from it. If you do, this card deals 1 damage to a recruited card that shares a field with the fortification.)</i>
<b>Reload</b> <i>(At the end of your deployment phase, if this card was deployed, you may remove an Ammo counter from it. If you do, place it back on the recruitment rail it was deployed from.)</i>
When this card is recruited, it gains 2 Ammo counters.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.003", "Ballista Crew", NULL, "Unit", NULL, "Ranged", "3", 2.0, NULL, NULL, "<b>Long-distance</b>, <b>Piercing</b>, <b>Reload</b> <i>(At the end of your deployment phase, if this card was deployed, you may remove an Ammo counter from it. If you do, place it back on the recruitment rail it was deployed from.)</i>
When this card is recruited, it gains 3 Ammo counters.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.004", "Ricochet", 1.0, "Order", NULL, "Ranged", "0", NULL, NULL, NULL, "Whenever an allied card would deal <b>Piercing</b> damage to a recruited card this turn, instead you may deal that damage to a different fortification that shares a lane with the original fortification the card attacked. ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.005", "Point-Blank", 2.0, "Order", NULL, "Ranged", "0", NULL, NULL, NULL, "The first time an allied card arrives at a fortification this turn, you may remove any number of Ammo counters from it. If you do, it gains {p} equal to the number of Ammo counters removed.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.006", "Flight Arrows", 1.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "<b>Ammo</b>
Target ranged card gains an Ammo counter and the <b>Long-distance</b> keyword until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.007", "Piercing Bolts", 1.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "<b>Ammo</b>
Target ranged card gains an Ammo counter and the <b>Piercing</b> keyword until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.008", "Shrapnel Shot", 1.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "The next time target ranged card would deal damage to a fortification this turn, that damage may instead be distributed to any number of recruited cards that share a field with the fortification.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.009", "Concussion Shot", 1.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "The next time target ranged card would deal damage to a recruited card this turn, instead remove that card from its recruitment rail.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.010", "Pick Off", 1.0, "Reinforcement", NULL, "Ranged", NULL, NULL, NULL, NULL, "Deal 1 damage to any card an opponent has recruited or deployed.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.011", "A Mile Away", 1.0, "Reinforcement", NULL, "Ranged", NULL, NULL, NULL, NULL, "Prevent all damage dealt to recruited allied cards that share a field with this reinforcement until the end of this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.012", "Exposed Sightline", 1.0, "Reinforcement", NULL, "Ranged", NULL, NULL, NULL, NULL, "Reveal target card an opponent controls that shares a field with this reinforcement.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.013", "Resupply Run", 1.0, "Reinforcement", NULL, "Ranged", NULL, NULL, NULL, NULL, "Target ranged card gains an Ammo counter.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.014", "Two in the Chamber", 1.0, "Response", NULL, "Ranged", "1", NULL, NULL, NULL, "<b>Trigger:</b> Allied <b>Ammo</b> card is played.
<b>Response:</b> You may play an additional <b>Ammo</b> card without paying its {c}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.015", "Watchful Sentry", 1.0, "Response", NULL, "Ranged", "1", NULL, NULL, NULL, "<b>Trigger:</b> Allied fortification is attacked by target card controlled by an opponent.
<b>Response:</b> Remove an ammo counter from a recruited allied ranged unit. If you do, deal damage equal to the unit's {p} to the target card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.016", "Bound Back", 1.0, "Response", NULL, "Ranged", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target <b>Long-distance</b> card arrives at a fortification and activates a reinforcement card.
<b>Response:</b> Redeploy target <b>Long-distance</b> card to the same lane and skip the arrival step. 
<i>(The activated reinforcement card's effect still resolves)</i>");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.017", "Bunker Buster Bolts", 2.0, "Order", NULL, "Ranged", "2", NULL, NULL, NULL, "<b>Ammo</b>
Target ranged card gains an Ammo counter and +1 {p} while attacking fortifications this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.018", "Arc Arrows", 2.0, "Order", NULL, "Ranged", "2", NULL, NULL, NULL, "<b>Ammo</b>
Target ranged card gains an Ammo counter and the first time it deals damage to a fortification this turn, deal 1 damage to all other fortifications controlled by an opponent.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.019", "Firing Line", 2.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "For each Ammo counter on cards you have recruited, deal 1 damage to a target fortification controlled by an opponent. You cannot declare deployments this turn.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.020", "Practice Makes Perfect", 1.0, "Order", NULL, "Ranged", "0", NULL, NULL, NULL, "Until the end of this turn, whenever an allied card would gain <b>Long-distance</b> or <b>Piercing</b> while already having the given keyword, place an Ammo counter on that card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.021", "Return Fire", 2.0, "Reinforcement", NULL, "Ranged", NULL, NULL, NULL, NULL, "The first time an attached fortification takes damage this turn, you may destroy an allied ranged unit on a recruitment rail that shares a field with the fortification. If you do, deal damage equal to your destroyed unit's {p} to all cards an opponent has recruited to that field.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.022", "Snare", 2.0, "Reinforcement", NULL, "Ranged", NULL, NULL, NULL, NULL, "Return the first card that arrives at an attached fortification to its recruitment rail and <b>equip</b> this card to it. While this is equipped, parent card cannot be deployed.
<b>Equip</b> <i>(Attach this card to another card. It remains attached until the parent card is destroyed.)</i>
<b>Once per Turn Order (1 {d}):</b> Destroy this card.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.023", "Scouting Report", 2.0, "Response", NULL, "Ranged", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target card is deployed.
<b>Response:</b> Target card skips the arrival step.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.024", "Push Through", 2.0, "Response", NULL, "Ranged", "0", NULL, NULL, NULL, "<b>Trigger:</b> Target <b>Piercing</b> card arrives at a fortification and activates a reinforcement card.
<b>Response:</b> Remove an Ammo counter from target card. If you do, negate the activated reinforcement card and destroy it.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.025", "One Bird With Two Stones", 2.0, "Response", NULL, "Ranged", "1", NULL, NULL, NULL, "<b>Trigger:</b> An <b>Ammo</b> card is played.
<b>Response:</b> You may search your deck for an <b>Ammo</b> card with the same name, and play it without paying its {c}.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.026", "Rain Hell", 3.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "Any number of <b>Long-distance</b> cards may be deployed to the same lane until the end of this turn. Any <b>Long-distance</b> card deployed this turn must skip the arrival step.");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.027", "Rapid Fire", 3.0, "Order", NULL, "Ranged", "1", NULL, NULL, NULL, "Whenever a ranged card arrives at a fortification this turn, you may discard a card. If you do, the arriving card attacks twice in the attack step until the end of this turn. (<i>You may choose different targets for the attacks</i>).");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.028", "Surplus Munitions", 3.0, "Response", NULL, "Ranged", "1", NULL, NULL, NULL, "<b>Trigger:</b> An <b>Ammo</b> card is played.
<b>Response:</b> Apply the effect of that <b>Ammo</b> card to all allied ranged cards.  ");
INSERT OR REPLACE INTO Cards(id, name, rank, type, class, attribute, cost, power, life, hand, text) VALUES ("ALP.RNG.029", "Ramparts", NULL, "Fortification", NULL, "Ranged", NULL, NULL, 7.0, NULL, "The first time a card arrives at this fortification each turn, you may destory a ranged card on an allied recruitment rail. If you do, deal 1 damage to the arriving card.");